{"metadata":{"externalID":"s:5Iden312NetworkErrorO07networkC0yACs0C0_pcACmF","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"networkError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"symbolKind":"case","title":"NetworkError.networkError(_:)","roleHeading":"Case","role":"symbol","modules":[{"name":"Iden3"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iden3\/networkerror\/networkerror(_:)"]}],"abstract":[{"type":"text","text":"Some error with the network call itself"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"networkError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}]}]}],"hierarchy":{"paths":[["doc:\/\/Iden3\/documentation\/Iden3","doc:\/\/Iden3\/documentation\/Iden3\/NetworkError"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/Iden3\/documentation\/Iden3\/NetworkError\/networkError(_:)"},"references":{"doc://Iden3/documentation/Iden3/NetworkError":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkError"}],"url":"\/documentation\/iden3\/networkerror","title":"NetworkError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkError","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"An error performing a network call"}],"kind":"symbol","identifier":"doc:\/\/Iden3\/documentation\/Iden3\/NetworkError"},"doc://Iden3/documentation/Iden3":{"role":"collection","kind":"symbol","type":"topic","title":"Iden3","abstract":[],"identifier":"doc:\/\/Iden3\/documentation\/Iden3","url":"\/documentation\/iden3"},"doc://Iden3/documentation/Iden3/NetworkError/networkError(_:)":{"role":"symbol","kind":"symbol","title":"NetworkError.networkError(_:)","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networkError","kind":"identifier"},{"kind":"text","text":"("},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Some error with the network call itself"}],"url":"\/documentation\/iden3\/networkerror\/networkerror(_:)","identifier":"doc:\/\/Iden3\/documentation\/Iden3\/NetworkError\/networkError(_:)"}}}